### PR TITLE
React-native upgrade

### PR DESCRIPTION
**Pull request by perry-mitchell**
Update react-native..

### CODE REVIEW

**Comment by Akimace** [comment]
hello,
there is possibility to minimise in windows toolbar ?

**Comment by perry-mitchell** [comment]
Hi @Akimace 

> there is possibility to minimise in windows toolbar ?

What do you mean by "windows toolbar"? 

This application is only for iOS and Android devices.

**Comment by perry-mitchell** [comment]
I'll be closing this PR as it is very outdated.

**Comment by Akimace** [comment]
Ah sorry, wrong place ! It's for desktop client (windows)

**Pull request closed without merging**
