### PR TITLE
Improve launcher icon display on Android

### PR DESCRIPTION
**Pull request by fortym2**
Hi,
This pull request fixes the default icon problem discussed in issue #145, and improves the square icon according to the [Material Design Guidelines](https://material.io/design/iconography/#grid-keyline-shapes) (keyline shapes)

Before|After
---|---
Before|After
Before|After

Let me know if it is okay :)

### CODE REVIEW

**Comment by perry-mitchell** [comment]
This is great @fortym2! I love the look of the icons. What do you think @sallar?

**Comment by fortym2** [comment]
Great! Happy to hear that :)

**Comment by perry-mitchell** [comment]
Hi @fortym2 - Seems I'm unable to publish this as I'm getting duplicate resources errors in Android Studio.. [This post](https://github.com/facebook/react-native/issues/22234#issuecomment-468545832) says to delete some of the assets but I'm not sure that that'll work.

image

Full log:

```
[drawable-xhdpi-v4/resources_images_search] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_search.png	[drawable-xhdpi-v4/resources_images_search] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_search.png: Error: Duplicate resources
[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_error] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_error.png	[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_error] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_error.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_menu] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_menu.png	[drawable-xhdpi-v4/resources_images_menu] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_menu.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_save] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_save.png	[drawable-xhdpi-v4/resources_images_save] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_save.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_bench] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_bench.png	[drawable-xhdpi-v4/resources_images_bench] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_bench.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_buttercupheader] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_buttercupheader.png	[drawable-xhdpi-v4/resources_images_buttercupheader] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_buttercupheader.png: Error: Duplicate resources
[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_info] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_info.png	[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_info] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_info.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_readonly] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_readonly.png	[drawable-xhdpi-v4/resources_images_readonly] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_readonly.png: Error: Duplicate resources
[drawable-xhdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/node_modules_reactnavigation_src_views_assets_backicon.png	[drawable-xhdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/node_modules_reactnavigation_src_views_assets_backicon.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_key] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_key.png	[drawable-xhdpi-v4/resources_images_key] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_key.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_boxes1] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_boxes1.png	[drawable-xhdpi-v4/resources_images_boxes1] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_boxes1.png: Error: Duplicate resources
[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_warn] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_warn.png	[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_warn] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_warn.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_solologo] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_solologo.png	[drawable-xhdpi-v4/resources_images_solologo] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_solologo.png: Error: Duplicate resources
[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_success] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_success.png	[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_success] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_success.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_globe] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_globe.png	[drawable-xhdpi-v4/resources_images_globe] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_globe.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_fingerprint] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_fingerprint.png	[drawable-xhdpi-v4/resources_images_fingerprint] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_fingerprint.png: Error: Duplicate resources
[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_cancel] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_cancel.png	[drawable-xhdpi-v4/node_modules_reactnativedropdownalert_assets_cancel] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/node_modules_reactnativedropdownalert_assets_cancel.png: Error: Duplicate resources
[drawable-xhdpi-v4/resources_images_locked] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xhdpi/resources_images_locked.png	[drawable-xhdpi-v4/resources_images_locked] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/resources_images_locked.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_search] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_search.png	[drawable-xxhdpi-v4/resources_images_search] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_search.png: Error: Duplicate resources
[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_error] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_error.png	[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_error] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_error.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_menu] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_menu.png	[drawable-xxhdpi-v4/resources_images_menu] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_menu.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_save] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_save.png	[drawable-xxhdpi-v4/resources_images_save] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_save.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_bench] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_bench.png	[drawable-xxhdpi-v4/resources_images_bench] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_bench.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_buttercupheader] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_buttercupheader.png	[drawable-xxhdpi-v4/resources_images_buttercupheader] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_buttercupheader.png: Error: Duplicate resources
[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_info] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_info.png	[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_info] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_info.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_readonly] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_readonly.png	[drawable-xxhdpi-v4/resources_images_readonly] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_readonly.png: Error: Duplicate resources
[drawable-xxhdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnavigation_src_views_assets_backicon.png	[drawable-xxhdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/node_modules_reactnavigation_src_views_assets_backicon.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_key] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_key.png	[drawable-xxhdpi-v4/resources_images_key] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_key.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_boxes1] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_boxes1.png	[drawable-xxhdpi-v4/resources_images_boxes1] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_boxes1.png: Error: Duplicate resources
[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_warn] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_warn.png	[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_warn] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_warn.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_solologo] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_solologo.png	[drawable-xxhdpi-v4/resources_images_solologo] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_solologo.png: Error: Duplicate resources
[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_success] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_success.png	[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_success] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_success.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_globe] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_globe.png	[drawable-xxhdpi-v4/resources_images_globe] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_globe.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_fingerprint] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_fingerprint.png	[drawable-xxhdpi-v4/resources_images_fingerprint] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_fingerprint.png: Error: Duplicate resources
[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_cancel] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_cancel.png	[drawable-xxhdpi-v4/node_modules_reactnativedropdownalert_assets_cancel] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/node_modules_reactnativedropdownalert_assets_cancel.png: Error: Duplicate resources
[drawable-xxhdpi-v4/resources_images_locked] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxhdpi/resources_images_locked.png	[drawable-xxhdpi-v4/resources_images_locked] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxhdpi/resources_images_locked.png: Error: Duplicate resources
[drawable-hdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-hdpi/node_modules_reactnavigation_src_views_assets_backicon.png	[drawable-hdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-hdpi/node_modules_reactnavigation_src_views_assets_backicon.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_webdav256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_webdav256.png	[drawable-mdpi-v4/resources_images_webdav256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_webdav256.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_search] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_search.png	[drawable-mdpi-v4/resources_images_search] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_search.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_entry256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_entry256.png	[drawable-mdpi-v4/resources_images_entry256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_entry256.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_trash256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_trash256.png	[drawable-mdpi-v4/resources_images_trash256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_trash256.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_error] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativedropdownalert_assets_error.png	[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_error] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativedropdownalert_assets_error.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_dropbox256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_dropbox256.png	[drawable-mdpi-v4/resources_images_dropbox256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_dropbox256.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_menu] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_menu.png	[drawable-mdpi-v4/resources_images_menu] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_menu.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_bell] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_bell.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_bell] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_bell.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_nextcloud256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_nextcloud256.png	[drawable-mdpi-v4/resources_images_nextcloud256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_nextcloud256.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_save] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_save.png	[drawable-mdpi-v4/resources_images_save] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_save.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_group256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_group256.png	[drawable-mdpi-v4/resources_images_group256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_group256.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_bench] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_bench.png	[drawable-mdpi-v4/resources_images_bench] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_bench.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_buttercupheader] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_buttercupheader.png	[drawable-mdpi-v4/resources_images_buttercupheader] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_buttercupheader.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_info] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativedropdownalert_assets_info.png	[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_info] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativedropdownalert_assets_info.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_bcup256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_bcup256.png	[drawable-mdpi-v4/resources_images_bcup256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_bcup256.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_readonly] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_readonly.png	[drawable-mdpi-v4/resources_images_readonly] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_readonly.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnavigation_src_views_assets_backicon.png	[drawable-mdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnavigation_src_views_assets_backicon.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_key] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_key.png	[drawable-mdpi-v4/resources_images_key] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_key.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_boxes1] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_boxes1.png	[drawable-mdpi-v4/resources_images_boxes1] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_boxes1.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_warn] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativedropdownalert_assets_warn.png	[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_warn] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativedropdownalert_assets_warn.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_file256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_file256.png	[drawable-mdpi-v4/resources_images_file256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_file256.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnavigation_src_views_assets_backiconmask] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnavigation_src_views_assets_backiconmask.png	[drawable-mdpi-v4/node_modules_reactnavigation_src_views_assets_backiconmask] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnavigation_src_views_assets_backiconmask.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_owncloud256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_owncloud256.png	[drawable-mdpi-v4/resources_images_owncloud256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_owncloud256.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_rocket] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_rocket.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_rocket] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_rocket.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_heart] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_heart.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_heart] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_heart.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_solologo] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_solologo.png	[drawable-mdpi-v4/resources_images_solologo] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_solologo.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_star] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_star.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_star] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_star.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_success] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativedropdownalert_assets_success.png	[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_success] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativedropdownalert_assets_success.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_globe] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_globe.png	[drawable-mdpi-v4/resources_images_globe] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_globe.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_fingerprint] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_fingerprint.png	[drawable-mdpi-v4/resources_images_fingerprint] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_fingerprint.png: Error: Duplicate resources
[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_cancel] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/node_modules_reactnativedropdownalert_assets_cancel.png	[drawable-mdpi-v4/node_modules_reactnativedropdownalert_assets_cancel] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/node_modules_reactnativedropdownalert_assets_cancel.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_locked] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_locked.png	[drawable-mdpi-v4/resources_images_locked] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_locked.png: Error: Duplicate resources
[drawable-mdpi-v4/resources_images_folder256] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-mdpi/resources_images_folder256.png	[drawable-mdpi-v4/resources_images_folder256] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-mdpi/resources_images_folder256.png: Error: Duplicate resources
[drawable-xxxhdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/src/main/res/drawable-xxxhdpi/node_modules_reactnavigation_src_views_assets_backicon.png	[drawable-xxxhdpi-v4/node_modules_reactnavigation_src_views_assets_backicon] /Users/perry/git/buttercup-mobile/android/app/build/generated/res/react/release/drawable-xxxhdpi/node_modules_reactnavigation_src_views_assets_backicon.png: Error: Duplicate resources
```

Any ideas?

**Comment by perry-mitchell** [comment]
Nevermind, seems we solved it.

**Pull request merged**
